name: widgets_extension
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

# name: forge
# description: 网络
# version: 0.0.5
# author: Tyrant
# homepage:

# environment:
#   sdk: ">=2.7.0 <3.0.0"
#   flutter: ">=1.17.0 <2.0.0"

# dependencies:
#   flutter:
#     sdk: flutter
#   json_annotation: ^4.0.0
#   dio: ^3.0.10
#   rxdart: ">=0.24.0 <1.0.0"

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   build_runner: ^1.0.0
#   json_serializable: ^4.1.1
  
# flutter:
